version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'eshop'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ~/mysql_data:/var/lib/mysql
  postgresqldb:
    image: postgres
    container_name: ca-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_very_strong_password
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - "5432:5432"
    networks:
      - postgres_network
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tests@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8889:80"
    volumes:
      - ~/pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_network
volumes:
  postgres-data:
  pgadmin-data:
  mysql-data:

networks:
  postgres_network:
    driver: bridge
  mysql_network:
    driver: bridge